const string TRADERPLUS_CONFIG_ROOT_SERVER = "$profile:TraderPlus\\";
const string TRADERPLUS_LOGGER_DIR_SERVER = TRADERPLUS_CONFIG_ROOT_SERVER + "TraderPlusLogs\\";
const string TRADERPLUS_LOGGER_PREFIX_SERVER = "TraderPlus_";
const string TRADERPLUS_CONFIG_DIR_SERVER = TRADERPLUS_CONFIG_ROOT_SERVER + "TraderPlusConfig\\";
const string TRADERPLUS_DB_DIR_SERVER = TRADERPLUS_CONFIG_ROOT_SERVER + "TraderPlusDatabase\\";
const string TRADERPLUS_CONFIG = TRADERPLUS_CONFIG_DIR_SERVER + "TraderPlusGeneralConfig.json";
const string TRADERPLUS_PRICE_CONFIG = TRADERPLUS_CONFIG_DIR_SERVER + "TraderPlusPriceConfig.json";
const string TRADERPLUS_ID_CONFIG = TRADERPLUS_CONFIG_DIR_SERVER + "TraderPlusIDsConfig.json";
const string TRADERPLUS_STOCK_CONFIG = TRADERPLUS_DB_DIR_SERVER + "TraderPlusStock_ID";
const string TRADERPLUS_VEHICULE_CONFIG =TRADERPLUS_CONFIG_DIR_SERVER + "TraderPlusVehiclesConfig.json";
const int TRADERPLUS_PLAYERS_QUEUETIME = 1000;

const float TRADERPLUS_QUEUE_TRANSACTION_INTERVAL = 0.5;
const float TRADERPLUS_TRANSACTION_INTERVAL = 1;

const int  TRADEMODE_SELL = 1;
const int  TRADEMODE_SELLVEHICLE = 2;
const int  TRADEMODE_BUY  = 0;

enum TraderPlusResponse
{
  SELL_SUCCESS=1,
  SELL_FAILED,
  BUY_SUCCESS,
  BUY_FAILED,
  NO_TRADE
}
